language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit.phar -c ./phpunit.xml --debug --verbose
  - ./vendor/bin/phpmd.phar ./src text ./phpmd.xml
  - ./vendor/bin/phpstan.phar analyse -l 7 ./src
  - ./vendor/bin/phpcpd.phar ./src
  - ./vendor/bin/phpcs.phar ./src --standard=PSR2
