language: php

php:
  - 7.1

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit.phar -c ./phpunit.xml --testdox
  - ./vendor/bin/phpstan.phar analyse -l max -c ./phpstan.neon ./src/
  - ./vendor/bin/phpcs.phar ./src --standard=PSR2
